apps/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.UserIndexView.as_view(), name='index'),
	url(r'^add/$', views.UserAddView.as_view(), name='add'),
	url(r'^view/(?P<pk>[0-9]+)/$', views.UserDetailView.as_view(), name='view'),
	url(r'^edit/(?P<pk>[0-9]+)/$', views.UserEditView.as_view(), name='edit'),
	url(r'^delete/(?P<pk>[0-9]+)/$', views.UserDeleteView.as_view(), name='delete'),
	url(r'^(?P<result>.*)$', views.UserIndexView.as_view(), name='index'),
]

videomonitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='camera/')),
    url(r'^camera/', include('apps.camera.urls', namespace='camera')),
    url(r'^login/', include('apps.login.urls', namespace='login')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]

apps/user/models.py
from django.db import models

# Create your models here.

apps/user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.forms import ModelForm, CharField, PasswordInput, ValidationError, HiddenInput
from django.utils.translation import ugettext_lazy as _


class UserForm(ModelForm):
	"""
	User form used to add or update a user in the Chronos platform.
	TODO: Develop this form
	"""

	password = CharField(widget=PasswordInput(), required=False)
	password_repeat = CharField(widget=PasswordInput(), required=False, )
	is_new_account = CharField(widget=HiddenInput(), required=False, )

	class Meta:

		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'is_staff', 'is_superuser', 'is_active']

	def clean(self):
		"""
		Function that adds additional functionality to the parent function clean() by
		validating the inputted passwords before returning the cleaned data.
		:return: The cleaned data
		"""

		cleaned_data = super(UserForm, self).clean()

		password = cleaned_data.get('password')
		password_repeat = cleaned_data.get('password_repeat')
		is_new_account = cleaned_data.get('is_new_account')

		if is_new_account:
			if not password:
				raise ValidationError(_("You must set a password for this account."), code='no password')

		if password or password_repeat:
			if password != password_repeat:
				raise ValidationError(_("The two password fields must match."), code='different_passwords')
			validate_password(password)

		return cleaned_data

	def save(self, commit=True):

		"""
		Function that adds additional functionality to the parent function save() by
		encrypting the user password before saving it in the database.
		:return: The cleaned data
		"""

		user = super(UserForm, self).save(commit=False)
		if self.cleaned_data["password"]:
			user.set_password(self.cleaned_data["password"])

		if commit:
			user.save()
		return user

apps/user/views.py
from datetime import datetime
from math import floor

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import password_validators_help_texts
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from apps.user.forms import UserForm

"""
User views created to manage the user CRUD operation.
"""


class UserIndexView(LoginRequiredMixin, ListView):
	"""
	View that is used to show all the users that exist in the Chronos platform.
	Receives optional parameters to show alert functions:
	@param result (optional) - Shows alert functions accordingly

		User added - YWRkZWQ=
		User edited - ZWRpdGVk
		User deleted - ZGVsZXRlZA==

	TODO: Develop this view
	"""

	template_name = 'user/user_index.html'
	model = User

	def get_alert_information(self):
		"""
		Function used to generate the alert string based on the return result by URL
		:return: String containing the result message
		"""
		if 'result' in self.kwargs:
			if self.kwargs['result'] == 'YWRkZWQ=':
				return _("A new user was added with success!")
			if self.kwargs['result'] == 'ZWRpdGVk':
				return _("The user information was edited with success!")
			if self.kwargs['result'] == 'ZGVsZXRlZA==':
				return _("The user information was deleted with success!")

	def get_context_data(self, **kwargs):
		context = super(UserIndexView, self).get_context_data(**kwargs)
		context['page_title'] = _('USERS')
		context['title'] = _('User list')
		context['user_active'] = 'active'
		context['result'] = self.get_alert_information()

		return context


class UserDetailView(LoginRequiredMixin, DetailView):
	"""
	View that is used to show the user information that exists in the Chronos platform.
	TODO: Develop this view
	"""

	template_name = "user/user_base.html"
	model = User

	def get_context_data(self, **kwargs):
		context = super(UserDetailView, self).get_context_data(**kwargs)
		context['page_title'] = _('USERS')
		context['title'] = _('User detail')
		context['user_active'] = 'active'
		context['progress'] = self.get_profile_completion()

		return context

	def get_profile_completion(self):
		"""
		This function is used to calculate the total percentage of the user's profile completion.
		:return: the calculated percentage
		"""
		user = self.get_object()
		filled_fields = 0
		total_fields = len(user._meta.fields)

		for field in user._meta.fields:
			if getattr(user, field.name):
				filled_fields += 1

		progression = floor((filled_fields / total_fields) * 100)

		return progression


class UserAddView(LoginRequiredMixin, CreateView):
	"""
	View that is used to add a new user in the Chronos platform.
	TODO: Develop this view
	"""

	model = User
	form_class = UserForm
	template_name = 'user/user_form.html'

	def get_context_data(self, **kwargs):
		context = super(UserAddView, self).get_context_data(**kwargs)
		context['page_title'] = _('USERS')
		context['title'] = _('Add new user')
		context['title'] = _('Add a new user')
		context['user_active'] = 'active'
		context['user_list'] = self.get_queryset()
		context['is_new_user'] = True
		context['help_text'] = password_validators_help_texts()

		return context

	def form_valid(self, form):
		return super(UserAddView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('user:index', kwargs={'result': 'YWRkZWQ='})


class UserEditView(LoginRequiredMixin, UpdateView):
	"""
	View that is used to edit an user in the Chronos platform.
	TODO: Develop this view
	"""

	model = User
	form_class = UserForm
	template_name = 'user/user_form.html'

	def get_context_data(self, **kwargs):
		context = super(UserEditView, self).get_context_data(**kwargs)
		context['page_title'] = _('USERS')
		context['title'] = _('Edit user')
		context['user_active'] = 'active'
		context['is_new_user'] = False
		context['help_text'] = password_validators_help_texts()

		return context

	def form_valid(self, form):
		return super(UserEditView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('user:index', kwargs={'result': 'ZWRpdGVk'})


class UserDeleteView(LoginRequiredMixin, DeleteView):
	"""
	View that is used to delete an user in the Chronos platform. Accessed via AJAX call
	TODO: Develop this view
	"""
	model = User
	template_name = 'user/user_delete_modal.html'

	def dispatch(self, *args, **kwargs):

		response = super(UserDeleteView, self).dispatch(*args, **kwargs)
		if self.request.is_ajax():
			response_data = {"result": "ok"}
			return JsonResponse(response_data)
		else:
			# POST request (not ajax) will do a redirect to success_url
			return response

	def get_success_url(self):
		return reverse_lazy('user:index', kwargs={'result': 'ZGVsZXRlZA=='})

apps/user/templates/user/user_base.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                        <div class="header">
                            <h4 class="title">{{ title }}</h4>
                        </div>
                        <div class="content">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "First name" %} </label>
                                        <p>{{ object.first_name }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Last name" %} </label>
                                        <p>{{ object.last_name }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Username" %} </label>
                                        <p>{{ object.username }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Email" %} </label>
                                        <p>{{ object.email }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Is staff?" %} </label>
                                        <p>{{ object.is_staff }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Is superuser?" %} </label>
                                        <p>{{ object.is_superuser }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Is active?" %} </label>
                                        <p>{{ object.is_active }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="content">
                        <a href="{% url "user:edit" object.pk %}" class="btn btn-success btn-fill btn-wd">{% trans "Edit user" %}</a>
                        <a href="{% url "user:index" %}" class="btn btn-danger btn-fill btn-wd">{% trans "Close" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/user/templates/user/user_delete_modal.html
{% load i18n %}
<div class="modal-dialog">
    <div class="modal-content">
        <form action="" method='POST'>
            {% csrf_token %}
            <div class="modal-header">
                <h4 class="modal-title">{% trans "Delete client" %}</h4>
            </div>
            <div class="modal-body">
                <p>
                    {% trans "Are you sure you would like to delete this client? You will not be able to undo this
                    operation!" %}
                </p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">{% trans "Delete" %}</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
            </div>
        </form>
    </div
</div>

apps/user/templates/user/user_form.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                <div class="header">
                    <h4 class="title">{{ title }}</h4>
                </div>
                <div class="content">
                    <form method='POST' role="form" action=''>
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="fa fa-times"></i>
                            </button>
                            {% for error in form.non_field_errors %}
                            <i class="fa fa-times"></i> {{ error }}
                            <br>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if is_new_account %}
                        {% render_field form.is_new_account value=is_new_account %}
                        {% endif %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.first_name.id_for_label }}'>{% trans "First name" %} </label>
                                    {% trans "First name" as first_name %}
                                    {% render_field form.first_name placeholder=first_name class="form-control border-input" %}
                                    {{ form.first_name.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.last_name.id_for_label }}'>{% trans "Last name" %} </label>
                                    {% trans "Last name" as last_name %}
                                    {% render_field form.last_name placeholder=last_name class="form-control border-input" %}
                                    {{ form.last_name.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.username.id_for_label }}'>{% trans "Username" %} </label>
                                    {% trans "Username" as username %}
                                    {% render_field form.username placeholder=username class="form-control border-input" %}
                                    {{ form.username.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.password.id_for_label }}'>{% trans "Password" %} </label>
                                    {% render_field form.password class="form-control border-input" %}
                                    {{ form.password.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.password_repeat.id_for_label }}'>{% trans "Repeat password" %} </label>
                                    {% render_field form.password_repeat class="form-control border-input" %}
                                    {{ form.password_repeat.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.email.id_for_label }}'>{% trans "Email" %} </label>
                                    {% trans "Email" as email %}
                                    {% render_field form.email placeholder=email class="form-control border-input" %}
                                    {{ form.email.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.is_staff.id_for_label }}'>{% trans "Is staff?" %} </label>
                                    {% render_field form.is_staff class="form-control border-input" %}
                                    {{ form.is_staff.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.is_superuser.id_for_label }}'>{% trans "Is superuser?" %} </label>
                                    {% render_field form.is_superuser class="form-control border-input" %}
                                    {{ form.is_superuser.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.is_active.id_for_label }}'>{% trans "Is active?" %} </label>
                                    {% render_field form.is_active class="form-control border-input" %}
                                    {{ form.is_active.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">
                                {% if is_new_camera %}
                                    {% trans "Submit" %}
                                    {% else %}
                                    {% trans "Update" %}
                                {% endif %}
                            </button>
                            <a href="{% url "user:index" %}" class="btn btn-danger btn-fill btn-wd">{% trans "Cancel" %}</a>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/user/templates/user/user_index.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                        <div class="header">
                            <h4 class="title">{{ title }}</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="content">
                        <a href="{% url "user:add" %}" class="btn btn-info btn-fill btn-wd">{% trans "Add new user" %}</a>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-12">
                    <table class="table table-striped">
                            <thead>
                                <th class="text-center">{% trans "ID" %}</th>
                                <th class="text-center">{% trans "First name" %}</th>
                                <th class="text-center">{% trans "Last name" %}</th>
                                <th class="text-center">{% trans "Username" %}</th>
                                <th class="text-center">{% trans "Email" %}</th>
                                <th class="text-center"></th>
                            </thead>
                            <tbody>
                            {% if object_list %}
                                {% for object in object_list %}
                                    <tr>
                                        <td class="text-center">{{ object.pk }}</td>
                                        <td class="text-center">{{ object.first_name }}</td>
                                        <td class="text-center">{{ object.last_name }}</td>
                                        <td class="text-center">{{ object.username }}</td>
                                        <td class="text-center">{{ object.email }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'user:view' object.pk %}" title="View user information" data-tooltip>
                                                <i class="ti-eye"></i>
                                            </a>
                                            <a href="{% url 'user:edit' object.pk %}" title="Edit user information" data-tooltip>
                                                <i class="ti-pencil"></i>
                                            </a>
                                            <a target="_blank" class="delete" href='{% url "user:delete" object.pk %}' title="Delete user information" data-tooltip>
                                                <i class="ti-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4"><p class="text-center small">(no data to display)</p></td>
                                </tr>
                            {% endif %}
                            </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block bottom %}
{% include "user/user_index_bottom_js.html" %}
{% endblock %}

apps/user/templates/user/user_index_bottom_js.html
{% load staticfiles compress i18n %}

{% compress js %}
<!-- inline scripts related to this page -->
<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    $(document).ready(function () {

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            crossDomain: false, // obviates need for sameOrigin test
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        var onDelete = function () {
            var url = this.href;
            $.confirm({
                closeIcon: true,
                columnClass: 'medium',
                icon: 'fa fa-warning',
                title: '{% trans "User deletion!" %}',
                content: '{% trans "<br/>Are you sure you want to <span class=\"text-danger\"> delete the camera information</span>?<br/>This cannot be undone!" %}',
                type: 'red',
                buttons: {
                    confirm: {
                        text: '{% trans "Delete" %}',
                        btnClass: 'btn-red',
                        action: function () {
                            $.post(url, function (data) {
                                if (data.result == "ok") {
                                    window.location.href = window.location.href.replace(/.*|$/, "ZGVsZXRlZA==");
                                } else {
                                    alert("smth goes wrong");
                                }
                            }).fail(function () {
                                alert("error");
                            });
                        },
                    },
                    cancel: {
                        text: '{% trans "Cancel" %}',
                        action: function () {
                        },
                    },
                }
            });
            return false;
        };

        $(".delete").click(onDelete);
    });
</script>
{% endcompress %}