apps/camera/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.CameraIndexView.as_view(), name='index'),
    url(r'^add/$', views.CameraAddView.as_view(), name='add'),
    url(r'^view/(?P<pk>[0-9]+)/$', views.CameraDetailView.as_view(), name='view'),
    url(r'^stream/(?P<pk>[0-9]+)/$', views.CameraStreamingView.as_view(), name='stream'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.CameraEditView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.CameraDeleteView.as_view(), name='delete'),
    url(r'^(?P<result>.*)$', views.CameraIndexView.as_view(), name='index'),
]

videomonitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='camera/')),
    url(r'^camera/', include('apps.camera.urls', namespace='camera')),
    url(r'^login/', include('apps.login.urls', namespace='login')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]

apps/camera/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class Camera(models.Model):
    """
    Camera table to be used by the Video Monitor platform.
    TODO: Develop this table
    """

    name = models.CharField('Name', max_length=255)
    description = models.TextField('Description', blank=True, null=True)
    comments = models.TextField('Comments', blank=True, null=True)
    vat = models.CharField('VAT', max_length=15, blank=True, null=True)
    url = models.CharField('URL', max_length=150, blank=True, null=True)
    created = models.DateTimeField('Created', default=now, blank=True, null=True)
    last_updated = models.DateTimeField('Last Updated', default=now, blank=True, null=True)
    is_visible = models.BooleanField('Is Visible')

    class Meta:
        # Translators: This string is used to identify the Client table name
        verbose_name = _('Camera')

        # Translators: This string is used to identify the Client table name in plural form
        verbose_name_plural = _('Cameras')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('view', kwargs={'pk': self.pk})

apps/camera/forms.py
from django.forms import ModelForm

from apps.camera.models import Camera


class CameraForm(ModelForm):
    """
    Camera form used to add or update a camera in the Video Monitor platform.
    TODO: Develop this form
    """

    class Meta:
        model = Camera
        fields = ['name', 'description', 'comments', 'url', 'is_visible']

apps/camera/views.py
from datetime import datetime
from math import floor

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from apps.camera.forms import CameraForm
from apps.camera.models import Camera

"""
Camera views created to manage the camera CRUD operation.
"""


class CameraIndexView(LoginRequiredMixin, ListView):
    """
    View that is used to show all the cameras that exist in the Video Monitor platform.
    Receives optional parameters to show alert functions:
    @param result (optional) - Shows alert functions accordingly

        Camera added - YWRkZWQ=
        Camera edited - ZWRpdGVk
        Camera deleted - ZGVsZXRlZA==

    TODO: Develop this view
    """

    template_name = 'camera/camera_index.html'
    model = Camera

    def get_alert_information(self):
        """
        Function used to generate the alert string based on the return result by URL
        :return: String containing the result message
        """
        if 'result' in self.kwargs:
            if self.kwargs['result'] == 'YWRkZWQ=':
                return _("A new camera was added with success!")
            if self.kwargs['result'] == 'ZWRpdGVk':
                return _("The camera information was edited with success!")
            if self.kwargs['result'] == 'ZGVsZXRlZA==':
                return _("The camera information was deleted with success!")

    def get_context_data(self, **kwargs):
        context = super(CameraIndexView, self).get_context_data(**kwargs)
        context['page_title'] = _('WEBCAMS')
        context['title'] = _('Webcam list')
        context['camera_active'] = 'active'
        context['result'] = self.get_alert_information()

        return context


class CameraDetailView(LoginRequiredMixin, DetailView):
    """
    View that is used to show the camera information that exists in the Video Monitor platform.
    TODO: Develop this view
    """

    template_name = "camera/camera_base.html"
    model = Camera

    def get_context_data(self, **kwargs):
        context = super(CameraDetailView, self).get_context_data(**kwargs)
        context['page_title'] = _('WEBCAMS')
        context['title'] = _('Webcam detail view')
        context['camera_active'] = 'active'
        context['progress'] = self.get_profile_completion()

        return context

    def get_profile_completion(self):
        """
        This function is used to calculate the total percentage of the camera's profile completion.
        :return: the calculated percentage
        """
        camera = self.get_object()
        filled_fields = 0
        total_fields = len(camera._meta.fields)

        for field in camera._meta.fields:
            if getattr(camera, field.name):
                filled_fields += 1

        progression = floor((filled_fields / total_fields) * 100)

        return progression

class CameraStreamingView(LoginRequiredMixin, DetailView):
    """
    View that is used to show the camera streaming in the Video Monitor platform.
    TODO: Develop this view
    """

    template_name = "camera/camera_streaming.html"
    model = Camera

    def get_context_data(self, **kwargs):
        context = super(CameraStreamingView, self).get_context_data(**kwargs)
        context['page_title'] = _('WEBCAMS')
        context['title'] = _('Webcam streaming view')
        context['camera_active'] = 'active'
        context['progress'] = self.get_profile_completion()

        return context

    def get_profile_completion(self):
        """
        This function is used to calculate the total percentage of the camera's profile completion.
        :return: the calculated percentage
        """
        camera = self.get_object()
        filled_fields = 0
        total_fields = len(camera._meta.fields)

        for field in camera._meta.fields:
            if getattr(camera, field.name):
                filled_fields += 1

        progression = floor((filled_fields / total_fields) * 100)

        return progression


class CameraAddView(LoginRequiredMixin, CreateView):
    """
    View that is used to add a new camera in the Video Monitor platform.
    TODO: Develop this view
    """

    model = Camera
    form_class = CameraForm
    template_name = 'camera/camera_form.html'

    def get_context_data(self, **kwargs):
        context = super(CameraAddView, self).get_context_data(**kwargs)
        context['page_title'] = _('WEBCAMS')
        context['title'] = _('Add a new webcam')
        context['camera_active'] = 'active'
        context['is_new_camera'] = True

        return context

    def form_valid(self, form):
        return super(CameraAddView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('camera:index', kwargs={'result': 'YWRkZWQ='})


class CameraEditView(LoginRequiredMixin, UpdateView):
    """
    View that is used to edit a camera in the Video Monitor platform.
    TODO: Develop this view
    """

    model = Camera
    form_class = CameraForm
    template_name = 'camera/camera_form.html'

    def get_context_data(self, **kwargs):
        context = super(CameraEditView, self).get_context_data(**kwargs)
        context['page_title'] = _('WEBCAMS')
        context['title'] = _('Edit webcam')
        context['camera_active'] = 'active '
        context['is_new_camera'] = False

        return context

    def form_valid(self, form):
        form.instance.last_updated = datetime.now()
        return super(CameraEditView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('camera:index', kwargs={'result': 'ZWRpdGVk'})


class CameraDeleteView(LoginRequiredMixin, DeleteView):
    """
    View that is used to delete a camera in the Video Monitor platform. Accessed via AJAX call
    TODO: Develop this view
    """
    model = Camera
    template_name = 'camera/camera_delete_modal.html'

    def dispatch(self, *args, **kwargs):

        id = self.get_object().id

        response = super(CameraDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            response_data = {"result": "ok", "id": id}
            return JsonResponse(response_data)
        else:
            # POST request (not ajax) will do a redirect to success_url
            return response

    def get_success_url(self):
        return reverse_lazy('camera:index', kwargs={'result': 'ZGVsZXRlZA=='})

apps/camera/templates/camera/camera_base.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                        <div class="header">
                            <h4 class="title">{{ title }}</h4>
                        </div>
                        <div class="content">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Name" %} </label>
                                        <p>{{ object.name }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "URL" %} </label>
                                        <p>{{ object.url }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Description" %} </label>
                                        <p>{{ object.description }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Comments" %} </label>
                                        <p>{{ object.comments }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="content">
                        <a href="{% url "camera:edit" object.pk %}" class="btn btn-success btn-fill btn-wd">{% trans "Edit camera" %}</a>
                        <a href="{% url "camera:index" %}" class="btn btn-danger btn-fill btn-wd">{% trans "Close" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/camera/templates/camera/camera_delete_modal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/camera/templates/camera/camera_form.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                <div class="header">
                    <h4 class="title">{{ title }}</h4>
                </div>
                <div class="content">
                    <form method='POST' role="form" action=''>
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="fa fa-times"></i>
                            </button>
                            {% for error in form.non_field_errors %}
                            <i class="fa fa-times"></i> {{ error }}
                            <br>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.name.id_for_label }}'>{% trans "Name" %} </label>
                                    {% trans "Camera name" as camera_name %}
                                    {% render_field form.name placeholder=camera_name class="form-control border-input" %}
                                    {{ form.name.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.url.id_for_label }}'>{% trans "URL" %} </label>
                                    {% trans "Camera url" as camera_url %}
                                    {% render_field form.url placeholder=camera_url class="form-control border-input" %}
                                    {{ form.url.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.description.id_for_label }}'>{% trans "Description" %} </label>
                                    {% trans "Camera description" as camera_description %}
                                    {% render_field form.description placeholder=camera_description class="form-control border-input" %}
                                    {{ form.description.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for='{{ form.comments.id_for_label }}'>{% trans "Comments" %} </label>
                                    {% trans "Camera comments" as camera_comments %}
                                    {% render_field form.comments placeholder=camera_comments class="form-control border-input" %}
                                    {{ form.comments.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">
                                {% if is_new_camera %}
                                    {% trans "Submit" %}
                                    {% else %}
                                    {% trans "Update" %}
                                {% endif %}
                            </button>
                            <a href="{% url "camera:index" %}" class="btn btn-danger btn-fill btn-wd">{% trans "Cancel" %}</a>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/camera/templates/camera/camera_index.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                        <div class="header">
                            <h4 class="title">{{ title }}</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="content">
                        <a href="{% url "camera:add" %}" class="btn btn-info btn-fill btn-wd">{% trans "Add new webcam" %}</a>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-12">
                    <table class="table table-striped">
                            <thead>
                                <th class="text-center">{% trans "ID" %}</th>
                                <th class="text-center">{% trans "Name" %}</th>
                                <th class="text-center">{% trans "URL" %}</th>
                                <th class="text-center"></th>
                            </thead>
                            <tbody>
                            {% if object_list %}
                                {% for object in object_list %}
                                    <tr>
                                        <td class="text-center">{{ object.pk }}</td>
                                        <td class="text-center">{{ object.name }}</td>
                                        <td class="text-center">{{ object.url }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'camera:view' object.pk %}" title="View camera information" data-tooltip>
                                                <i class="ti-eye"></i>
                                            </a>
                                            <a href="{% url 'camera:stream' object.pk %}" title="View camera stream" data-tooltip>
                                                <i class="ti-video-camera"></i>
                                            </a>
                                            <a href="{% url 'camera:edit' object.pk %}" title="Edit camera information" data-tooltip>
                                                <i class="ti-pencil"></i>
                                            </a>
                                            <a target="_blank" class="delete" href='{% url "camera:delete" object.pk %}' title="Delete camera information" data-tooltip>
                                                <i class="ti-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4"><p class="text-center small">(no data to display)</p></td>
                                </tr>
                            {% endif %}
                            </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block bottom %}
{% include "camera/camera_index_bottom_js.html" %}
{% endblock %}

apps/camera/templates/camera/camera_index_bottom_js.html
{% load staticfiles compress i18n %}

{% compress js %}
<!-- inline scripts related to this page -->
<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    $(document).ready(function () {

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            crossDomain: false, // obviates need for sameOrigin test
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        var onDelete = function () {
            var url = this.href;
            $.confirm({
                closeIcon: true,
                columnClass: 'medium',
                icon: 'fa fa-warning',
                title: '{% trans "User deletion!" %}',
                content: '{% trans "<br/>Are you sure you want to <span class=\"text-danger\"> delete the camera information</span>?<br/>This cannot be undone!" %}',
                type: 'red',
                buttons: {
                    confirm: {
                        text: '{% trans "Delete" %}',
                        btnClass: 'btn-red',
                        action: function () {
                            $.post(url, function (data) {
                                if (data.result == "ok") {
                                    window.location.href = window.location.href.replace(/.*|$/, "ZGVsZXRlZA==");
                                } else {
                                    alert("smth goes wrong");
                                }
                            }).fail(function () {
                                alert("error");
                            });
                        },
                    },
                    cancel: {
                        text: '{% trans "Cancel" %}',
                        action: function () {
                        },
                    },
                }
            });
            return false;
        };

        $(".delete").click(onDelete);
    });
</script>
{% endcompress %}

apps/camera/templates/camera/camera_streaming.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block header %}
{% include "core/header_styles.html" %}
{% include "camera/camera_streaming_bottom_styles.html" %}
{% include "core/header_js.html" %}
{% endblock %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="col-lg-12 col-md-12">
                        <div class="header">
                            <h4 class="title">{{ title }}</h4>
                        </div>
                        <div class="content">
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <h5>{% trans "Video Stream" %}</h5>
                                        <div id="my_video_{{object.pk}}"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "URL" %} </label>
                                        <p>{{ object.url }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Description" %} </label>
                                        <p>{{ object.description }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>{% trans "Comments" %} </label>
                                        <p>{{ object.comments }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="container-fluid">
                    <div class="content">
                        <a href="{% url "camera:edit" object.pk %}" class="btn btn-success btn-fill btn-wd">{% trans "Edit camera" %}</a>
                        <a href="{% url "camera:index" %}" class="btn btn-danger btn-fill btn-wd">{% trans "Close" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block bottom %}
{% include "camera/camera_streaming_bottom_js.html" %}
{% endblock %}

apps/camera/templates/camera/camera_streaming_bottom_js.html
{% load staticfiles compress i18n %}

{% compress js %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js"></script>
<script>
var player = new Clappr.Player(
    {
        source: "{{object.url}}",
        parentId: "#my_video_{{object.pk}}",
        actualLiveTime: true,
        crossOrigin: 'use-credentials',
        hlsMinimumDvrSize: 0,
    });
</script>
{% endcompress %}

apps/camera/templates/camera/camera_streaming_bottom_styles.html
{% load staticfiles compress %}

{% compress css %}
{% endcompress %}