apps/login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='index'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

apps/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.UserIndexView.as_view(), name='index'),
	url(r'^add/$', views.UserAddView.as_view(), name='add'),
	url(r'^view/(?P<pk>[0-9]+)/$', views.UserDetailView.as_view(), name='view'),
	url(r'^edit/(?P<pk>[0-9]+)/$', views.UserEditView.as_view(), name='edit'),
	url(r'^delete/(?P<pk>[0-9]+)/$', views.UserDeleteView.as_view(), name='delete'),
	url(r'^(?P<result>.*)$', views.UserIndexView.as_view(), name='index'),
]

videomonitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='camera/')),
    url(r'^camera/', include('apps.camera.urls', namespace='camera')),
    url(r'^login/', include('apps.login.urls', namespace='login')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
]

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render

# Create your views here.

apps/core/templates/core/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>{{ page_title }}</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    {% block header %}
    {% include "core/header_styles.html" %}
    {% include "core/header_js.html" %}
    {% endblock %}
</head>
<body>
{% block siderbar %}
{% include "core/sidebar.html" %}
{% endblock %}
<div class="wrapper">
    <div class="main-panel" id="main-panel">
        {% block navigation %}
        {% include "core/navigation.html" %}
        {% endblock %}
        {% block content %}
        {% endblock %}
        {% block footer %}
        {% include "core/footer.html" %}
        {% endblock %}
    </div><!-- /.main-panel -->
</div><!-- /.wrapper -->
{% include "core/bottom_js.html" %}
{% block bottom %}
{% endblock %}
</body>
</html>

apps/core/templates/core/bottom_js.html
{% load staticfiles compress %}

{% compress js %}

<!--   Core JS Files   -->
<script src='{% static "core/js/jquery-1.10.2.js" %}' type="text/javascript"></script>
<script src='{% static "core/js/bootstrap.min.js" %}' type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src='{% static "core/js/bootstrap-checkbox-radio.js" %}'></script>

<!--  Charts Plugin -->
<script src='{% static "core/js/chartist.min.js" %}'></script>

<!--  Notifications Plugin    -->
<script src='{% static "core/js/bootstrap-notify.js" %}'></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<!-- JQuery Confirm Plugin -->
<script src='{% static "core/js/jquery-confirm.min.js" %}'></script>

<!-- Paper Dashboard Core javascript -->
<script src='{% static "core/js/paper-dashboard.js" %}'></script>

{% endcompress %}

apps/core/templates/core/footer.html
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>

                <li>
                    <a href="http://www.creative-tim.com">
                        Template by Creative Tim
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script>, made with <i class="fa fa-heart heart"></i> by Hélder Pestana
        </div>
    </div>
</footer>

apps/core/templates/core/header_js.html
{% load staticfiles compress %}

{% compress js %}

{% endcompress %}

apps/core/templates/core/header_styles.html
{% load staticfiles compress %}

{% compress css %}


<!-- Bootstrap core CSS     -->
<link href='{% static "core/css/bootstrap.min.css" %}' rel="stylesheet" />

<!-- Animation library for notifications   -->
<link href='{% static "core/css/animate.min.css" %}' rel="stylesheet"/>

<!-- JQuery Confirm plugin css   -->
<link href='{% static "core/css/jquery-confirm.min.css" %}' rel="stylesheet"/>

<!--  Paper Dashboard core CSS    -->
<link href='{% static "core/css/paper-dashboard.css" %}' rel="stylesheet"/>

<!--  Fonts and icons     -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
<link href='{% static "core/css/themify-icons.css" %}' rel="stylesheet">

{% endcompress %}

apps/core/templates/core/navigation.html
{% load i18n %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">{{ page_title }}</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href='{% url "user:view" user.pk %}'>
                        <i class="ti-user"></i>
                        <p>{{ user.username }}</p>
                    </a>
                </li>
                <li>
                    <a href='{% url "login:logout" %}'>
                        <i class="ti-power-off"></i>
                        <p>{% trans "Logout" %}</p>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

apps/core/templates/core/sidebar.html
{% load i18n%}

<div class="sidebar" data-background-color="white" data-active-color="danger">

<!--
    Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
    Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

    <div class="sidebar-wrapper">
        <div class="logo">
            <a href='#' class="simple-text">
                VIDEO MONITOR
            </a>
        </div>

        <ul class="nav">
            <!--<li class="{{ dashboard_active }}">
                <a href="dashboard.html">
                    <i class="ti-panel"></i>
                    <p>Dashboard</p>
                </a>
            </li>!-->
            <li class="{{ camera_active }}">
                <a href='{% url "camera:index" %}'>
                    <i class="ti-video-camera"></i>
                    <p>Webcams</p>
                </a>
            </li>
             <li class="{{ user_active }}">
                <a href='{% url "user:index" %}'>
                    <i class="ti-user"></i>
                    <p>Users</p>
                </a>
            </li>
        </ul>
    </div>
</div>